# Introduction

Diabetes is one of the top causes of death worldwide. Combined with obesity and hypertension, it tends to take the form of cardiovascular diseases, the leading causes of death worldwide [@khan2017validity]. India has the second-largest population of people who have diabetes. 64.5 million people had diabetes in 2017, and the number of diabetics is projected to increase to 87 million by 2030 [@dudeja2017diabetes]. The number of people who have diabetes is higher in the urban parts of India compared to the rural regions. In a metropolitan area, a person is twice as likely to suffer from diabetes. The more susceptible people are the ones living in urban slums rather than the wealthy urban class. This is mainly caused due to lack of information about nutrition and proper diet. 

In diabetes, the most common type of diabetes found is type two diabetes, accounting for more than 90 percent of the diabetic population. Among the people who have type two diabetes, over 50 percent never get diagnosed. According to the International Diabetes Federation, about 66 percent of Indians making up the diabetic population (44 Lakhs) were unaware they had diabetes. This makes this group of individuals have an increased risk of complications. @kahn2010age, in a study, have determined that screening people for diabetes improves their quality of life.

A few known reasons for the escalation of the diabetes problem in India are greater resistance to insulin, strong genetic factors, and environmental factors due to urbanization:
Studies by @yajnik1995fetal have shown that low birth weight is associated with higher insulin resistance among Indians. His studies have also demonstrated that Indian newborns have higher insulin levels than European newborns. One more factor attributed to this is accelerated childhood growth. A follow-up study has supported these findings and has concluded that lower birth weight, with obesity, leads to very high rates of diabetes.
Genetic susceptibility does play an essential role in the occurrence of Type two diabetes. Biologically, Indians are known to have unfavorable phenotypes and risk profiles for type 2 diabetes and coronary artery diseases, thus making them more prone to the conditions. Due to these factors, diabetes also develops at least a decade or two earlier among Indians than Europeans, which is considerably higher. Despite all the evidence suggesting genetic factors' role among Indians, the genetic shift is a slow process. Without long-term follow-up studies, a conclusive statement cannot be made about the current diabetes situation with respect to genetic factors.
The role of environmental factors is also a serious factor that cannot be overlooked in a study for diabetes. India is undergoing rapid urbanization, with urbanization rates at 35 percent. This has led to increased consumption of foods rich in fats, sugars, and calories. This, combined with high levels of mental stress, is not a good sign regarding insulin sensitivity and obesity. Studies have also shown that the possibility of incurring diabetes in India was lower among people with lower incomes and much more among people from affluent groups.

It has also been observed that physical inactivity is linked with a higher probability of incurring diabetes. This is one of the reasons the rural population of India, which has a physically active lifestyle, does not suffer from diabetes as much as the urban population, which has a comparatively sedentary lifestyle. A study by @misra2001high has reported that migration from rural areas to slums in urban areas leads to obesity and glucose intolerance, which intensify the problem of diabetes. 

In India, urbanization and economic growth have caused a change in dietary patterns. Traditional patterns are being replaced by industrially manufactured packaged food. Greater intake of such high-calorie items has put many at risk of developing diabetes and coronary artery diseases.

The objective of this study is to identify the determinants that exhibit a significant impact on the likelihood of diabetes incidence. To this end, a dataset from the National Institute of Diabetes and Kidney Diseases, comprising variables such as age, BMI, and number of pregnancies, among others, has been utilized. We have employed Multiple Linear Regression to assess the effect of these variables. Our model scrutinizes the significance of independent variables at 10 percent, 5 percent, and 1 percent levels on the outcome, namely, the propensity of diabetes occurrence. Diagnostic tests, including Heteroskedasticity, Omitted Variable Bias, and Multicollinearity have been conducted to ensure the credibility of our model.